name: CI class

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Chekout do código
      uses: actions/chekout@v2

    - name: Configurar NodeJs
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: Instalar dependencias
      run: npm install
    
    - name: Executar teste
      run: npm test
      